name: tflint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: terraform-linters/setup-tflint@v3
      - uses: terraform-linters/tflint-load-config-action@v1
        with:
          source-repo: me/tflint-config
      - run: tflint -f compact
